/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xbird_util_lang_SystemUtils */

#ifndef _Included_xbird_util_lang_SystemUtils
#define _Included_xbird_util_lang_SystemUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xbird_util_lang_SystemUtils
 * Method:    getProcessCpuTime_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xbird_util_lang_SystemUtils__getProcessCpuTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
