/*
 * @(#)$Id$
 *
 * Copyright 2008 Makoto YUI
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * Contributors:
 *     Makoto YUI - reversely generated from XQJ javadoc using codavaj
 */
package javax.xml.xquery;

/**
 * An object that registers to be notified of events generated by a
 * PooledXQConnection object. The XQConnectionEventListener interface is
 * implemented by a connection pooling component. A connection pooling component
 * will usually be provided by an XQJ vendor or by another system software
 * vendor. An XQJ implementation notifies an XQConnectionEventListener object
 * when an application is finished using a pooled connection with which the
 * listener has registered. The notification occurs after the application calls
 * the method close on its representation of a PooledXQConnection object. An
 * XQConnectionEventListener is also notified when a connection error occurs due
 * to the fact that the PooledXQConnection is unfit for future use - the network
 * connection to the XML datasource died, for example. The listener is notified
 * by the XQJ implementation just before it throws an XQException to the
 * application using the PooledXQConnection object.
 */
public interface XQConnectionEventListener {
    /**
     * Notifies this XQConnectionEventListener that the application has called
     * the method close on its representation of a pooled connection.
     */
    void connectionClosed(XQConnectionEvent event);

    /**
     * Notifies this XQConnectionEventListener that a fatal error has occurred
     * and the pooled connection can no longer be used. The XQJ implementation
     * makes this notification just before it throws the application the
     * XQException contained in the given XQConnectionEvent object.
     */
    void connectionErrorOccurred(XQConnectionEvent event);

}
